name: devops

services:
  rabbitmq:
    container_name: devops-rabbitmq
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "15272:5672"
      - "15273:15672"
    mem_limit: 256m

  mysql:
    container_name: devops-database
    image: mysql:8.0
    ports:
      - "13316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: devops-control-plane
    volumes:
      - ./data/mysql/conf:/var/lib/mysql
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/init:/docker-entrypoint-initdb.d
    mem_limit: 256m
